---
title: "Labs"
---

R Labs

* Lab 1 : [Overview & Getting Started](labs/lab1_overview.html)
* Lab 2 : [Learning R with the Help of AI tools Starting with Graphing using ggplot](labs/lab2_AI_ggplot.html)
* Lab 3 : [Data Transformation with dplyr](labs/lab3_data_transformation.qmd)
* Lab 4 : [Coding Basics, Style and Data Read/Write](labs/lab4_coding_import.qmd)
* Lab 5 : [Working with NEON Metagenome Assembled Genomes (MAGs / bins)](labs/lab5_NEON_tables.qmd)
* Lab 6 : [ggplotting with NEON MAG data](labs/lab6_NEON_pub_graphics.html)
* Lab 7 : [Data Tidying, Transformation and Visualization with COVID-19 reporting data](labs/lab7_covid.html)
* Lab 8: Catch up, [What will viruses do next?](https://www.nature.com/articles/d41586-024-04195-3), [the first AI genomes](https://arcinstitute.org/news/hie-king-first-synthetic-phage) and [metagenome brainstorming](https://lucid.app/lucidspark/c06e7281-775f-42fe-af28-575afe457a40/edit?invitationId=inv_197475dd-6f27-44b7-9a22-805928e4acdc)
* Lab 9 : Phylogenetic tree visualization using ggtree
* Lab 10 : Read abundance - normalization and statistics

Unity Labs

* Lab : Running bioinformatics software on Unity (Blast, Read mapping) 

Sharing and Publishing

* Lab S1 : [Quarto](labs/lab1s_quarto.html)
* Lab S2 : [Adding References to Your Report with Zotero](labs/lab2s_biblio.html)
* Lab : Connecting a Github repo site with a RStudio project
* Lab : Quarto Manuscripts
* Lab : Building a 5 tab web site with Quarto
* Lab : R Shiny

Manuscript

* PathoGen manuscript : Deadline Dec 10